
class TargetException(Exception):
    pass

class BattleException(Exception):
    pass
